- name: Install (Red Hat/CentOS) Apache Web Server
  yum: pkg=httpd state=latest
  when: "ansible_os_family == 'RedHat'"
  notify: Restart HTTPD
  ignore_errors: yes
- name: Install (Debian/Ubuntu) Apache Web Server
  apt: pkg=apache2 state=latest
  when: "ansible_os_family == 'Debian'"
  ignore_errors: yes
