---

- hosts: dev
  become: yes
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: latest
    - name:
      service:
        name: httpd
        state: started
        enabled: yes
    - name: add a line to index.html
      file:
        path: /var/www/html/index.html
        state: touch
    - name: add a line to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Hello world!"
